.TH INTERNSCTL 1 "October 2023"
.SH NAME
internsctl \- Custom Linux Command for Interns
.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]
.SH DESCRIPTION
.B internsctl
is a custom Linux command that provides various functionalities for interns.
.PP
Available options include:
.TP
\fB\-\-help\fR
Display usage information.
.TP
\fB\-\-version\fR
Display the command version.
.TP
\fB\-\-greet\fR
Greet the interns.
.TP
\fB\-\-report\fR
Generate a report for the interns.
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Display this help message.
.TP
\fB\-\-version\fR
Display the version of internsctl.
.TP
\fB\-\-greet\fR
Greet the interns.
.TP
\fB\-\-report\fR
Generate a report for the interns.
.PP
.SH EXAMPLES
Display the version of internsctl:
.RS
.B internsctl \-\-version
.RE
.PP
Greet the interns:
.RS
.B internsctl \-\-greet
.RE
.PP
Generate a report for the interns:
.RS
.B internsctl \-\-report
.RE
.PP
.SH SEE ALSO
.BR bash (1)
.SH AUTHOR
Rishav Chauhan
